### ISSUE TITLE
> at begin of line freezes SublimeText

### ISSUE THREAD

**Issue by arnauldvm** [mrchief/AsciiDoc.SublimeText2#8]
Typing the character '>' at the beginning of a line freezes SublimeText.

Typing a space foolowed by the character '>' at the beginning of a line, then deleting the space freezes SublimeText.

- SublimeText 2.0.2, Build 2221, Windows 7
- AsciiDoc package for Sublime Text2 v2013.07.01.20.56.30

**Comment by mrchief** [comment]
Duplicate of #5?
