### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [mrchief/AsciiDoc.SublimeText2#9]
I would like to use your grammar for AsciiDoc but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by pchaigno** [comment]
@mrchief Did you get a chance to look into this? I'm considering using your grammar at [github/linguist](https://github.com/github/linguist) to highlight AsciiDoc code on GitHub.

**Comment by mrchief** [comment]
@pchaigno Sorry I totally missed this. I would go with a MIT license. I'll add it to the repo to make it explicit. If you need anything else or run into any issues, let me know.

**Comment by mrchief** [comment]
361d9c038bf62d7a3267e0e59cd6fddd661281d1 fixes this.

**Comment by pchaigno** [comment]
Perfect! Thanks!
